parameters:

services:
    Luckyseven\Bundle\LuckysevenJwtAuthBundle\Service\JwtAuthService:
        arguments:
            $params: '@parameter_bag'
            $JWTManager: '@lexik_jwt_authentication.jwt_manager'
            $refreshTokenManager: '@gesdinet.jwtrefreshtoken.refresh_token_manager'
            $refreshTokenGenerator: '@gesdinet.jwtrefreshtoken.refresh_token_generator'
            $attachRefreshTokenOnSuccessListener: '@gesdinet.jwtrefreshtoken.send_token'
